"""
pdf_generator.py — Genera documentos clínicos en PDF usando ReportLab.
Devuelve la URL pública del archivo generado para que el agente pueda
presentársela al doctor como enlace de descarga.
"""

import os
import re
import uuid
import json
from datetime import datetime
from dotenv import load_dotenv

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing, Line

# Cargar variables de entorno
load_dotenv()

# Google Cloud Storage Configuration
_BUCKET_NAME = os.getenv("BUCKET_NAME", "")

# Directorio donde se almacenan los PDFs
_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_PDF_DIR = os.path.abspath(os.path.join(_BASE_DIR, "static", "documents"))

# URL base del servidor — ajustable via variable de entorno
_SERVER_URL = os.getenv("PUBLIC_SERVER_URL", "http://localhost:8080")

# ---------------------------------------------------------------------------
# Textos bilingues
# ---------------------------------------------------------------------------
_LABELS = {
    "es": {
        "receta":       "RECETA MÉDICA",
        "presupuesto":  "PRESUPUESTO DENTAL",
        "tratamiento":  "PLAN DE TRATAMIENTO",
        "header":       "ODONTO-ORACLE — SISTEMA CLÍNICO INTELIGENTE",
        "paciente":     "DATOS DEL PACIENTE",
        "diagnostico":  "DIAGNÓSTICO",
        "prescripcion": "PRESCRIPCIÓN",
        "tratamiento_sec": "PLAN DE TRATAMIENTO",
        "presupuesto_sec": "PARTIDAS DEL PRESUPUESTO",
        "doctor":       "FIRMA DEL MÉDICO RESPONSABLE",
        "fecha":        "Fecha de Emisión",
        "id_clinico":   "ID Clínico",
        "telefono":     "Teléfono",
        "alergias":     "Alergias",
        "clinica":      "Clínica",
        "footer":       "Documento clínico generado por Odonto-Oracle · Confidencial",
    },
    "en": {
        "receta":       "MEDICAL PRESCRIPTION",
        "presupuesto":  "DENTAL ESTIMATE",
        "tratamiento":  "TREATMENT PLAN",
        "header":       "ODONTO-ORACLE — INTELLIGENT CLINICAL SYSTEM",
        "paciente":     "PATIENT DATA",
        "diagnostico":  "DIAGNOSIS",
        "prescripcion": "PRESCRIPTION",
        "tratamiento_sec": "TREATMENT PLAN",
        "presupuesto_sec": "ESTIMATE DETAILS",
        "doctor":       "RESPONSIBLE PHYSICIAN SIGNATURE",
        "fecha":        "Issue Date",
        "id_clinico":   "Clinical ID",
        "telefono":     "Phone",
        "alergias":     "Allergies",
        "clinica":      "Clinic",
        "footer":       "Clinical document generated by Odonto-Oracle · Confidential",
    }
}


def generar_documento_clinico(
    tipo_documento: str,
    datos_paciente: dict,
    contenido_medico: str,
    idioma: str,
) -> str:
    """
    Genera un PDF clínico premium en blanco y negro con ReportLab.
    Retorna la URL pública del documento generado o un error descriptivo.
    """
    try:
        # Desempaquetado recursivo de datos_paciente
        for _ in range(5):
            if not isinstance(datos_paciente, dict):
                break
            if "paciente" in datos_paciente and isinstance(datos_paciente["paciente"], dict):
                datos_paciente = datos_paciente["paciente"]
            elif "data" in datos_paciente and isinstance(datos_paciente["data"], dict):
                datos_paciente = datos_paciente["data"]
            else:
                break

        if not tipo_documento:
            return "System Error: Falta el tipo de documento (receta, presupuesto, tratamiento)."
        if not datos_paciente or not datos_paciente.get("nombre"):
            return "System Error: Faltan los datos del paciente. Busca primero al paciente con buscar_paciente."
        if not contenido_medico:
            return "System Error: Falta el contenido medico del documento."

        lang = idioma.lower() if idioma and idioma.lower() in ["es", "en"] else "es"
        labels = _LABELS[lang]
        tipo = tipo_documento.lower().strip()
        titulo = labels.get(tipo, labels["receta"])

        # Asegurar directorio
        os.makedirs(_PDF_DIR, exist_ok=True)

        # Nombre único
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        uid = uuid.uuid4().hex[:6]
        file_name = f"{tipo}_{ts}_{uid}.pdf"
        file_path = os.path.abspath(os.path.normpath(os.path.join(_PDF_DIR, file_name)))

        # Cargar el nombre del doctor y de la clínica dinámicamente (Settings-First Source of Truth)
        clinica_id = datos_paciente.get("clinica_id", "OO-CLINIC-001")
        
        # 1. Valores por defecto base
        nombre_doctor = "Dentista Responsable"
        nombre_clinica = "Odonto-Oracle"
        settings_loaded = False

        # 2. Intentar cargar desde el archivo de configuración de la clínica
        try:
            settings_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "static", f"settings_{clinica_id}.json"))
            if os.path.exists(settings_path):
                with open(settings_path, "r", encoding="utf-8") as sf:
                    s_data = json.load(sf)
                    nombre_doctor = s_data.get("nombre_doctor") or s_data.get("nombre_dentista") or nombre_doctor
                    nombre_clinica = s_data.get("nombre_clinica") or nombre_clinica
                    settings_loaded = True
            else:
                # Fallback general
                general_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "static", "settings.json"))
                if os.path.exists(general_path):
                    with open(general_path, "r", encoding="utf-8") as sf:
                        s_data = json.load(sf)
                        nombre_doctor = s_data.get("nombre_doctor") or s_data.get("nombre_dentista") or nombre_doctor
                        nombre_clinica = s_data.get("nombre_clinica") or nombre_clinica
                        settings_loaded = True
        except Exception as e:
            print(f"[PDF GENERATOR] Warning: No se pudo leer la configuración de settings: {e}")

        # 3. Si settings no cargaron o tienen valores genéricos, y datos_paciente provee valores específicos (que no sean el ID técnico)
        if (not settings_loaded or nombre_doctor == "Dentista Responsable") and datos_paciente.get("nombre_doctor"):
            nombre_doctor = datos_paciente.get("nombre_doctor")
            
        if (not settings_loaded or nombre_clinica == "Odonto-Oracle") and datos_paciente.get("nombre_clinica"):
            p_clinica = datos_paciente.get("nombre_clinica")
            # Ignorar si es id técnico que empieza con user_
            if p_clinica and not p_clinica.startswith("user_"):
                nombre_clinica = p_clinica

        # Normalizar el prefijo Dr./Dra. para evitar duplicados en la firma
        doctor_display = nombre_doctor.strip()
        if not (doctor_display.lower().startswith("dr.") or doctor_display.lower().startswith("dra.") or doctor_display.lower().startswith("dr ") or doctor_display.lower().startswith("dra ")):
            doctor_display = f"Dr. {doctor_display}"

        # Documento ReportLab
        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Paleta estrictamente corporativa en blanco y negro (tonos oscuros y grises limpios)
        color_primary = colors.HexColor("#0f0f0f")
        color_secondary = colors.HexColor("#333333")

        # Estilos tipográficos
        title_style = ParagraphStyle(
            "ClinicalTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=color_primary,
            alignment=1, # Centrado
            spaceAfter=4,
        )

        subtitle_style = ParagraphStyle(
            "ClinicalSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#555555"),
            alignment=1, # Centrado
            spaceAfter=15,
        )

        section_header_style = ParagraphStyle(
            "ClinicalSectionHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=color_primary,
            spaceAfter=6,
            keepWithNext=True
        )

        body_text_style = ParagraphStyle(
            "ClinicalBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=color_secondary,
        )

        body_bold_style = ParagraphStyle(
            "ClinicalBodyBold",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=color_primary,
        )

        signature_title_style = ParagraphStyle(
            "ClinicalSignatureTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=color_primary,
            alignment=1, # Centrado
        )

        signature_doctor_style = ParagraphStyle(
            "ClinicalSignatureDoctor",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=color_secondary,
            alignment=1, # Centrado
        )

        story = []

        # 1. Encabezado Centrado
        story.append(Paragraph(titulo, title_style))
        clinica_header = f"{nombre_clinica.upper()} — SISTEMA CLÍNICO INTELIGENTE" if lang == "es" else f"{nombre_clinica.upper()} — INTELLIGENT CLINICAL SYSTEM"
        story.append(Paragraph(clinica_header, subtitle_style))

        # 2. Línea Horizontal Divisoria (Drawing con Line)
        d = Drawing(504, 8)
        d.add(Line(0, 4, 504, 4, strokeColor=color_primary, strokeWidth=1.5))
        story.append(d)
        story.append(Spacer(1, 12))

        # 3. DATOS DEL PACIENTE Section
        story.append(Paragraph(labels["paciente"], section_header_style))
        
        # Construir tabla de metadatos del paciente
        paciente_info = [
            [
                Paragraph("<b>Paciente:</b>", body_bold_style),
                Paragraph(datos_paciente.get("nombre", ""), body_text_style),
                Paragraph(f"<b>{labels['fecha']}:</b>", body_bold_style),
                Paragraph(datetime.now().strftime("%d/%m/%Y %H:%M"), body_text_style),
            ],
            [
                Paragraph(f"<b>{labels['id_clinico']}:</b>", body_bold_style),
                Paragraph(datos_paciente.get("paciente_id", "") or "—", body_text_style),
                Paragraph(f"<b>{labels['telefono']}:</b>", body_bold_style),
                Paragraph(datos_paciente.get("telefono", "") or "—", body_text_style),
            ],
            [
                Paragraph(f"<b>{labels['alergias']}:</b>", body_bold_style),
                Paragraph(datos_paciente.get("alergias", "") or "—", body_text_style),
                Paragraph(f"<b>{labels['clinica']}:</b>", body_bold_style),
                Paragraph(nombre_clinica, body_text_style),
            ]
        ]
        
        t_paciente = Table(paciente_info, colWidths=[80, 172, 80, 172])
        t_paciente.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e5e5")),
        ]))
        story.append(t_paciente)
        story.append(Spacer(1, 15))

        # Procesar y separar DIAGNÓSTICO de PRESCRIPCIÓN/CONTENIDO
        diagnostico_txt = "Revisión dental y diagnóstico preventivo general."
        contenido_principal_txt = contenido_medico

        # Lógica de extracción inteligente para separar las secciones si vienen juntas en el texto
        lower_content = contenido_medico.lower()
        if "diagnóstico:" in lower_content or "diagnostico:" in lower_content:
            parts = re.split(r"(?i)diagnós?tico:", contenido_medico, maxsplit=2)
            if len(parts) > 1:
                subparts = re.split(r"(?i)(prescripción|prescripcion|tratamiento|indicaciones|plan de tratamiento|partidas|costo):", parts[1], maxsplit=2)
                diagnostico_txt = subparts[0].strip()
                if len(subparts) > 2:
                    contenido_principal_txt = subparts[2].strip()
                else:
                    contenido_principal_txt = parts[1].strip()
        elif "recetó:" in lower_content or "prescribió:" in lower_content:
            parts = re.split(r"(?i)(recetó|prescribió|prescripcion|prescripción):", contenido_medico, maxsplit=2)
            diagnostico_txt = parts[0].strip()
            if len(parts) > 2:
                contenido_principal_txt = parts[2].strip()

        # 4. DIAGNÓSTICO Section
        story.append(Paragraph(labels["diagnostico"], section_header_style))
        story.append(Paragraph(diagnostico_txt, body_text_style))
        story.append(Spacer(1, 15))

        # 5. CONTENIDO PRINCIPAL Section (PRESCRIPCIÓN, PLAN DE TRATAMIENTO o PRESUPUESTO)
        tipo_sec = "prescripcion"
        if tipo == "presupuesto":
            tipo_sec = "presupuesto_sec"
        elif tipo == "tratamiento":
            tipo_sec = "tratamiento_sec"
            
        story.append(Paragraph(labels[tipo_sec], section_header_style))
        story.append(Paragraph(contenido_principal_txt.replace("\n", "<br/>"), body_text_style))
        story.append(Spacer(1, 30))

        # 6. FIRMA DEL MÉDICO RESPONSABLE (CENTRADAS EN EL PDF)
        story.append(Spacer(1, 25))
        
        firma_data = [
            [Paragraph(labels["doctor"], signature_title_style)],
            [Paragraph(doctor_display, signature_doctor_style)]
        ]
        t_firma = Table(firma_data, colWidths=[250])
        t_firma.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('LINEABOVE', (0,0), (-1,0), 1, color_primary), # Elegant B&W solid divider line above text
        ]))
        t_firma.hAlign = 'CENTER'
        story.append(t_firma)

        # Construir PDF físico
        doc.build(story)

        # Asegurar escritura física inmediata en Windows usando fsync
        try:
            fd = os.open(file_path, os.O_RDWR | os.O_BINARY)
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
            print("[PDF GENERATOR] >>> Escrito y sincronizado físicamente en disco (os.fsync exitoso).")
        except Exception as fsync_err:
            print(f"[PDF GENERATOR] Warning: No se pudo realizar fsync sobre el archivo: {fsync_err}")

        # Intentar subir a Google Cloud Storage si BUCKET_NAME está configurado
        if _BUCKET_NAME:
            try:
                from google.cloud import storage
                print(f"[PDF GENERATOR] >>> Subiendo a Google Cloud Storage (Bucket: {_BUCKET_NAME})...")
                client = storage.Client()
                bucket = client.bucket(_BUCKET_NAME)
                blob = bucket.blob(file_name)
                # Subir archivo
                blob.upload_from_filename(file_path, content_type='application/pdf')
                
                # Generar URL pública permanente de GCS
                url_publica = f"https://storage.googleapis.com/{_BUCKET_NAME}/{file_name}"
                print(f"[PDF GENERATOR] >>> Subida a GCS exitosa. URL: {url_publica}")
                
                # Eliminar archivo local para liberar memoria
                try:
                    os.remove(file_path)
                    print("[PDF GENERATOR] >>> Archivo local eliminado del contenedor.")
                except Exception as del_err:
                    print(f"[PDF GENERATOR] Warning: No se pudo eliminar el archivo local: {del_err}")
                    
                return (
                    f"Success: Documento '{titulo}' generado exitosamente. "
                    f"URL de descarga: {url_publica}"
                )
            except Exception as gcs_err:
                print(f"[PDF GENERATOR] Error al subir a GCS: {str(gcs_err)}")
                print("[PDF GENERATOR] >>> Cayendo en fallback de almacenamiento local...")

        # Fallback local
        print(f"\n[PDF GENERATOR] >>> DOCUMENTO CLÍNICO GUARDADO FÍSICAMENTE EN: {os.path.abspath(file_path)}")
        print(f"[PDF GENERATOR] >>> ACCESIBLE PÚBLICAMENTE EN LA URL: {_SERVER_URL}/static/documents/{file_name}\n")

        url_publica = f"{_SERVER_URL}/static/documents/{file_name}"
        return (
            f"Success: Documento '{titulo}' generado exitosamente. "
            f"URL de descarga: {url_publica}"
        )

    except Exception as e:
        return (
            f"System Error: No se pudo generar el PDF. Detalle técnico: {str(e)}. "
            "Verifica que el contenido médico y los datos del paciente estén completos."
        )
